In [23]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.arange(0, 20)
arr3 = np.linspace(1, 5, 10)

print(arr1)
print(arr2)
print(arr3)


[10 20 30 40 50]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [24]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
empty = np.empty((2, 2))
identity = np.identity(3)

print(zeros)
print(ones)
print(empty)
print(identity)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 2.  7.]
 [12. 17.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

arr1_float = arr1.astype(float)
print(arr1_float.dtype)

print(arr1.mean())
print(reshaped.mean(axis=1))


int64
int64
float64
float64
30.0
[ 2.  7. 12. 17.]


In [26]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

reshaped = arr2.reshape(4, 5)
print(reshaped)


(5,)
(20,)
(10,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
gradient = np.gradient(arr3)
print(gradient)

conditions = [
    arr1 < 10,
    (arr1 >= 10) & (arr1 <= 30),
    arr1 > 30
]

choices = ["Low", "Medium", "High"]

classified = np.select(conditions, choices, default="Unknow")
print(classified)

appended = np.append(arr1, [60, 70, 80])
print(appended)


[0.44444444 0.44444444 0.44444444 0.44444444 0.44444444 0.44444444
 0.44444444 0.44444444 0.44444444 0.44444444]
['Medium' 'Medium' 'Medium' 'High' 'High']
[10 20 30 40 50 60 70 80]
